language: php

php:
- 7.2

before_install:
- composer global require hirak/prestissimo

install:
- sudo apt-get install lftp fontforge
- composer self-update
- composer install
- nvm install 9
- npm install --global grunt-cli
- npm install
- cd vendor/redaxscript/redaxscript-template && npm install && cd -
- cd vendor/redaxscript/redaxscript && npm install && cd -

script:
- replace 'vendor/redaxscript' '..' -- vendor/redaxscript/redaxscript-template/templates/redaxscript/assets/styles/_redaxscript.css
- grunt build --gruntfile vendor/redaxscript/redaxscript-template/gruntfile.js
- grunt build --gruntfile vendor/redaxscript/redaxscript/gruntfile.js
- grunt
- grunt config

after_success:
- grunt deploy
- grunt trigger

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
