language: php

php: 7.2

addons:
 apt:
  packages:
  - lftp

before_install:
- composer global require hirak/prestissimo

install:
- composer install
- nvm install 14
- npm install --global grunt-cli
- npm install
- cd vendor/redaxscript/redaxscript-template && npm install && cd -
- cd vendor/redaxscript/redaxscript && npm install && cd -

script:
- replace 'vendor/redaxscript' '..' -- vendor/redaxscript/redaxscript-template/templates/redaxscript/assets/styles/_redaxscript.css
- grunt build --gruntfile vendor/redaxscript/redaxscript-template/gruntfile.js
- grunt build --gruntfile vendor/redaxscript/redaxscript/gruntfile.js
- grunt
- grunt config
- grunt lock

after_success:
- grunt deploy
- grunt trigger

notifications:
 email:
 - team@redaxscript.com
