language: php

php:
- 7.1

before_install:
- composer global require hirak/prestissimo

install:
- sudo apt-get install lftp fontforge
- composer self-update
- composer install
- nvm install 6
- npm install --global ied
- npm install --global grunt-cli
- IED_CACHE_DIR=.tmp ied install
- cd vendor/redaxmedia/redaxscript-template && IED_CACHE_DIR=.tmp ied install && cd -
- cd vendor/redaxmedia/redaxscript && IED_CACHE_DIR=.tmp ied install && cd -

script:
- replace 'vendor/redaxmedia' '..' -- vendor/redaxmedia/redaxscript-template/templates/redaxscript/assets/styles/_redaxscript.css
- grunt build --gruntfile vendor/redaxmedia/redaxscript-template/gruntfile.js
- grunt build --gruntfile vendor/redaxmedia/redaxscript/gruntfile.js
- grunt
- grunt config

after_success:
- lftp $FTP_URL -e "glob -d mirror build . --reverse --delete-first --parallel=10 && chmod 0444 config.php && exit"
- grunt trigger

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
